config/routes.rb
Rails.application.routes.draw do
  root 'urls#new'

  get '/:id', to: 'home#index', as: 'redirect'

  resources :urls, only: [:create, :new, :show]

end

app/models/url.rb
class Url < ActiveRecord::Base
end

app/controllers/api/v1/api_controller.rb
class Api::V1::ApiController < ApplicationController
  respond_to :json
  # TODO: authentication stuff would go here
end

app/controllers/api/v1/artists_controller.rb
module Api
  module V1
    class ArtistsController < ApiController

      def index
        render json: Artist.all, status: :ok
      end

      def search
        term = params[:term] || nil
        if term
          artists = Artist.where(
            "name LIKE :term OR handle LIKE :term OR tags LIKE :term OR location LIKE :term", term: "%#{term}%"
          )
        else
          artists = Artist.all
        end

        render json: artists, status: :ok

      end
      
      # TODO: if i had more time, add the rest of the CRUD operations for the artists resource


      private

    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if params[:id]
      url = Url.find(params[:id])
      url.update(hits: url.hits+1)
      redirect_to url.original_url
    else
      redirect_to new_url_path, notice: "Enter a url to shorten!"
    end
  end
end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController

  def show
    @url = Url.find(params[:id])
  end

  def new
    @url = Url.new
  end

  def create
    @url = Url.new(url_params)
    respond_to do |format|
      if @url.save
        format.html { redirect_to url_path(@url), notice: 'Your url was submitted. Check it out!' }
      else
        format.html { redirect_to new_url_path, notice: "Your url was incorrectly formatted, please try again" }
      end
    end
  end

  private
    def url_params
      params.require(:url).permit(:original_url)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class="container">
  <%= form_for @url, html: {class: 'form-horizontal'} do |f| %>
    <div class="field">
      <%= f.label :original_url %><br />
      <%= f.text_field :original_url, autofocus: true, class: "form-control" %>
    </div>
</div>

<script type="text/javascript">


function searchArtists(filterValue) {
  $.ajax({
    type: 'GET',
    dataType: 'json',
    url: ``,
    success: function(data) {
      populateResults(data);
    }
  });

}

function populateResults(data){
  $('.heading').text(`Results (${data.length})`);
  html = "";
  $.each(data, function (key,val) {
    html += ``;
  });
  $('.complete').html(html);
}

</script>

app/views/layouts/_google_analytics.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', '<%= ENV['GOOGLE_ANALYTICS_ID'] %>', 'auto');
  ga('send', 'pageview');
</script>

app/views/layouts/_nav.html.erb
<nav class="navbar fixed-top navbar-light bg-light">
  <a class="navbar-brand" href="/">Url Shortener</a>
  <ul class="nav navbar-nav navbar-right">
  </ul>
</nav>

app/views/layouts/_notification.html.erb
<div class="notification">
  <% flash.each do |name, msg| %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>  alert-dismissable">
      <button type="button" class="close close-notification" data-dismiss="alert" aria-hidden="true">&times;</button>
      <strong><%= msg %></strong>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Url Shortener</title>
  <%= javascript_include_tag 'application' %>
  <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js"></script>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js" integrity="sha512-K1qjQ+NcF2TYO/eI3M6v8EiNYZfA95pQumfvcVrTHtwQVDG+aHRqLi/ETn2uB+1JqwYqVG3LIvdm9lj6imS/pQ==" crossorigin="anonymous"></script>

  <!-- Latest compiled and minified JavaScript -->
  <%= csrf_meta_tags %>
  <!-- this is always required for mobile responsiveness! -->
  <meta charset="utf-8" name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
  <%= render 'layouts/nav' %>
  <%= render 'layouts/notification' %>
  <%= yield %>
  <%= render 'layouts/google_analytics' %>

</body>
</html>

app/views/urls/new.html.erb
<div class="container">
  <div class="field-holder">
    <h3>Enter your URL below:</h3>
    <%= form_for @url, html: {class: 'form-horizontal'} do |f| %>
      <div class="field">
        <%= f.text_field :original_url, autofocus: true, class: "form-control" %>
      </div>
      <div class="actions">
        <%= f.submit "Shorten!", class: "btn shorten" %>
      </div>
    <% end %>
  </div>
</div>

app/views/urls/show.html.erb
<div class="container">
<div class="field-holder">
  <div class="copied">Copied!</div>
  <h3>Your URL:</h3>
  <div class="input-group">
    <input type="text" class="form-control" id="resultUrl" value="<%= redirect_url(@url.id)%>" readonly>
    <span class="input-group-btn">
      <button class="btn btn-default" type="button" id="clipboard">Copy to Clipboard!</button>
    </span>
  </div><!-- /input-group -->
</div>
<div class="field-holder">
  <h3 class="">URL Stats:</h3>
  <table class="table table-dark">
    <thead>
      <tr><th scope="col"># of times unshortened</th></tr>
    </thead>
    <tbody>
      <tr><td scope="row"> <%= @url.hits %> </td></tr>
    </tbody>
  </table>

</div>

<script type="text/javascript">
  $('#clipboard').click(function(){
    copyClipboard();
  })

  function copyClipboard() {
    copyText = document.querySelector("#resultUrl");
    copyText.select();
    document.execCommand("Copy");

    flashCopied()
  }

  function flashCopied() {
    $(".copied").slideDown().delay(1400).slideUp()
  }
</script>